---
title: "Cetaceans Species Distribution"
author: "Anastasia Kunz"
date: "2/21/2021"
output: 
  html_document:
    theme: flatly
    code_folding: hide 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(raster)
library(tidyverse)
library(here)
library(sf)
library(fasterize)
library(rnaturalearth)

```

```{r, echo = TRUE, results = "hide"}
coastline <- ne_download(scale = 50, type = 'land', category = 'physical', returnclass = "sf")
```


```{r}
cetaceans <- list.files(path = "ca_cetaceans", full.names = TRUE)


#create a stack of all rasters
cetaceans_rast <- raster::stack(cetaceans)

# create the vector containing elements to make a matrix
reclass <- c(0, 0.59, 0, 0.6, 1, 1)

#make the matrix out of the vector
matrix_reclass <- matrix(reclass, ncol = 3, byrow = TRUE)

#reclassify the rasters in the stack based on the threshold
presence_rast <- reclassify(cetaceans_rast, matrix_reclass)

# add up all the values from the reclassified rasters into a single raster
rast_sum <- raster::calc(cetaceans_rast, fun = sum, na.rm = TRUE)

species_sum_df <-  raster::rasterToPoints(rast_sum) %>% 
  as.data.frame()


```

```{r, fig.cap= ""}

ggplot()+
  geom_raster(data = species_sum_df, aes(x = x, y = y, fill = layer))+
  scale_fill_gradient("Species Richness", low = "darkblue", high = "cyan2") +
  geom_sf(data = coastline, fill = "navajowhite3")+
  coord_sf(xlim = c(-124.8,-115.5), ylim = c(32,38)) +
  theme_minimal()+
  labs(
    x = " ",
    y = " ",
    title = "California Cetaceans Species Richness"
  )
  
```




